import TileGroup from './TileGroup'
import IconRect from '../../ui/tiles/IconRect'

export default function TechStackTiles() {
    return (
        <TileGroup head="Tech Stack" className="tech-stack">
            <IconRect
                type="full"
                icon="Node"
                label="Node.js"
                bgColor="#83cd29"
                className="tech-stack-node"
            />
            <IconRect
                type="badge"
                icon="Express"
                label="Express.js"
                bgColor="black"
                className="tech-stack-express"
            />
            <IconRect
                type="badge"
                icon="Jest"
                label="Jest"
                bgColor="#99425b"
                className="tech-stack-jest"
            />
            <IconRect
                type="badge"
                icon="PostgresSQL"
                label="PostgresSQL"
                bgColor="#336791"
                className="tech-stack-pg"
            />
            <IconRect
                type="badge"
                icon="Swagger"
                label="Swagger"
                bgColor="#85ea2d"
                className="tech-stack-swagger"
            />
            <IconRect
                type="full"
                icon="React"
                label="React.js"
                bgColor="#61dafb"
                className="tech-stack-react"
            />
            <IconRect
                type="badge"
                icon="Sass"
                label="Sass"
                bgColor="#cb6699"
                className="tech-stack-sass"
            />
            <IconRect
                type="badge"
                icon="Redux"
                label="Redux"
                bgColor="#764abc"
                className="tech-stack-redux"
            />
            <IconRect
                type="badge"
                icon="ReactQuery"
                label="ReactQuery"
                bgColor="#764abc"
                className="tech-stack-react-query"
            />
            <IconRect
                type="badge"
                icon="Vite"
                label="Vite"
                bgColor="#764abc"
                className="tech-stack-vite"
            />
            <IconRect
                type="full"
                icon="AWS"
                label="AWS"
                bgColor="#252f3e"
                className="tech-stack-aws"
            />
            <IconRect
                type="full"
                icon="TypeScript"
                label="TypeScript"
                bgColor="#007acc"
                className="tech-stack-typescript"
            />
        </TileGroup>
    )
}
